import type { Metadata } from "next";
import { Inter } from "next/font/google";
import WebSocket from "./WebSocket";
import QueryProvider from "./QueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "지금이니",
  description: "Generated by create 지금이니",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <WebSocket />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
